# config/packages/security.yaml
security:
    # Configuration des encodeurs de mots de passe (optionnel pour notre cas)
    password_hashers:
        # Utilisation d'un hasher simple pour les mots de passe en dur
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs d'utilisateurs (nous n'en avons pas besoin avec l'auth personnalisée)
    providers:
        # Fournisseur vide car nous gérons l'auth manuellement
        app_user_provider:
            memory:
                users: {}

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                # ...
                # This line is probably the cause of the redirect to the wrong route
                default_target_path: app_job_status_visualization # Or some other route name
            
            # Pas de configuration d'authentification automatique
            # car nous gérons tout manuellement
            
            # Configuration de la déconnexion
            logout:
                path: app_logout
                target: app_login

    # Contrôle d'accès (optionnel avec notre système manuel)
    access_control:
        # Permettre l'accès à la page de login
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/check-auth, roles: PUBLIC_ACCESS }
        
        # Toutes les autres routes nécessitent une authentification
        # (géré par notre AuthenticationListener)
        # - { path: ^/, roles: ROLE_USER }

