# config/services.yaml
parameters:
    locale: 'fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # This is the only explicit service definition you need for this to work.
        # ... (The App\Controller\: section should be right above this)

    App\EventListener\AuthenticationListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 8 }

    App\Twig\AuthExtension:
        tags: ['twig.extension']

